### ISSUE TITLE
Bug in d3xp-player.def for handgrenades

### ISSUE THREAD

**Issue by 63564365** [mjsonofharry/RBDOOM-3-BFG-Gameplay-Overhaul#78]
In d3xp-player.def, 

`"weapon7_cycle"						"1"`
should be
`"weapon7_cycle"						"0"`

This avoids grenades being thrown when cycling through weapons (e.g. by using the mousewheel)

player.def has this implemented correctly, so this only manifests when playing the "Resurrection of Evil" campaign.

**Comment by mjsonofharry** [comment]
Thanks for catching this and creating PR #79 
I've approved and merged your fix.
